DEFAULT onikiri
TIMEOUT 1
MENU TITLE Onikiri Mk.I

LABEL onikiri
    LINUX /Image
    INITRD /initramfs.cpio.gz
    FDT /sun50i-h616-onikiri.dtb
    APPEND console=ttyS0,115200n8 console=tty1 video=HDMI-A-1:1024x600M@60e root=/dev/ram0 rdinit=/init rofs_device=/dev/mmcblk0p2 loglevel=7 ignore_loglevel fbcon=map:0 drm.debug=0x3f zswap.enabled=1 zswap.compressor=lz4 usbcore.autosuspend=-1 coherent_pool=2M cma=32M panic=10
